---

apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  labels:
    run: gitlab
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30080
      name: http
    - port: 443
      protocol: TCP
      nodePort: 30043
      name: https
    - port: 22
      protocol: TCP
      nodePort: 30022
      name: ssh
  selector:
    run: gitlab

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      run: gitlab
  replicas: 1
  template:
    metadata:
      labels:
        run: gitlab
    spec:
      containers:
        - name: gitlab
         #image: https://gitlab.vahe.home/admin/projects/root/iot-test-for-inception-of-things_iot
          image: gitlab/gitlab-ce:11.10.4-ce.0
          ports:
            - containerPort: 443
            - containerPort: 80
            - containerPort: 22

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-app
  namespace: argocd
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.vahe.home/root/iot-test-for-inception-of-things_iot.git 
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:  #make it sync with git
      prune: true  #to remove any manual change made.
      selfHeal: true  #to remove pod if it's not used anymore.

