Vagrant.configure("2") do |config|

        config.vm.define "miarzumaS" do |miarzumaS|
        config.vm.box = "generic/alpine311"
            miarzumaS.vm.hostname = "miarzumaS"
            miarzumaS.vm.synced_folder ".", "/vagrant"
            miarzumaS.vm.network "private_network", ip: "192.168.56.110"
            miarzumaS.vm.provision "shell", privileged: true, path: "scripts/server.sh", args: ["192.168.56.110"]
            miarzumaS.vm.provider "virtualbox" do |vb|
              vb.name = "miarzumaS"
              vb.memory = "2048"
              vb.cpus = "2"
            end
        end

        config.vm.define "miarzumaSW" do |miarzumaSW|
        config.vm.box = "generic/alpine311"
            miarzumaSW.vm.hostname = "miarzumaSW"
            miarzumaSW.vm.synced_folder ".", "/vagrant"
            miarzumaSW.vm.network "private_network", ip: "192.168.56.111"
            miarzumaSW.vm.provision "shell", privileged: true, path: "scripts/sworker.sh", args:  ["192.168.56.110", "192.168.56.111"]
            miarzumaSW.vm.provider "virtualbox" do |vb|
              vb.name = "miarzumaSW"
              vb.memory = "2048"
              vb.cpus = "2"
            end
        end

    end
