apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: paulbouwer/hello-kubernetes:1.10
        imagePullPolicy: IfNotPresent
        env: 
        - name: MESSAGE
          value: "Hello from app-one."

          
# Это конфигурация развертывания Kubernetes. Вот разбивка того, что он делает:

# apiVersion: apps/v1: указывает версию API Kubernetes, которую вы используете для создания этого объекта.

# kind: Deployment: это означает, что вы создаете развертывание, которое представляет собой объект Kubernetes, представляющий набор идентичных модулей.

# metadata: этот раздел содержит данные, которые помогают однозначно идентифицировать объект, включая name(имя развертывания) и labels(пары «ключ-значение», которые можно использовать для организации и выбора подмножеств объектов).

# spec: Этот раздел определяет желаемое состояние объекта.

# replicas: 1: указывает, что вы хотите, чтобы работала одна копия вашего модуля. Если модуль по какой-либо причине выйдет из строя, развертывание обеспечит его замену новым.

# selector: так развертывание определяет, какими модулями нужно управлять. В данном случае выбираются модули с меткой app: app-1.

# template: это шаблон, который будет использоваться для создания модулей, которыми управляет это развертывание.

# Итак, вкратце, это развертывание создаст один модуль, на котором будет работать paulbouwer/hello-kubernetes:1.10образ Docker, с переменной среды, MESSAGEустановленной на «Hello from app-one». Если модуль выйдет из строя по какой-либо причине, развертывание обеспечит его замену новым.

