Vagrant.configure("2") do |config|

        config.vm.define "miarzumaS" do |miarzumaS|
        config.vm.box = "generic/alpine311"
            miarzumaS.vm.hostname = "miarzumaS"
            miarzumaS.vm.synced_folder ".", "/vagrant"
            miarzumaS.vm.network "private_network", ip: "192.168.56.110"
            miarzumaS.vm.provision "shell", privileged: true, path: "setup_script.sh", args: ["192.168.56.110"]
            miarzumaS.vm.provider "virtualbox" do |vb|
              vb.name = "miarzumaS"
              vb.memory = "2048"
              vb.cpus = "2"
            end
        end
end
